---
- name: NFS mount to fstab
  hosts: all
  become: true
  
  tasks:
    - name: NFS share folder is exist?
      ansible.builtin.file:
        path: "/data/comp/"
        state: directory
        permission: '0777'
    
    - name: NFS mount to fstab
      ansible.posix.mount:
        path: "/data/dir"
        src: "10.0.2.15:/nfs/share"
        fstype: nfs
        opts: "rw,sync"
        state: mounted
        