---
- name: All user must change password except root
  hosts: all
  become: true
  
  vars:
    user_name: "user_name,!root"
    user_pass: "password"
    
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ user_name }}"
          notify:
            - username check
        password: "{{ user_pass | password_hash('sha512') }}"
        
  handler:
    - name: username check
      ansible.builtin.user:
        name: "{{ user_name }}"
        state: present
    